Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.63.63"
  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = "2048"
  end
end
