apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: environment-variables
    envs:
      - variables.env
replacements:
  - source:
      kind: ConfigMap
      name: environment-variables
      fieldPath: data.APP_VERSION
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.[name=main].image
        options:
          delimiter: ":"
          index: 1
resources:
  - web
